[0m09:05:38.271135 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F02A5797C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F02A579AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F02A57A9C0>]}


============================== 09:05:38.274846 | 9a2e902b-4e85-43dc-8e07-bfc0f4b2965f ==============================
[0m09:05:38.274846 [info ] [MainThread]: Running with dbt=1.7.11
[0m09:05:38.274846 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\adolfo.arcoya\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:05:50.693297 [debug] [MainThread]: Starter project path: C:\dbt\.dbt\Lib\site-packages\dbt\include\starter_project
[0m09:05:50.811499 [info ] [MainThread]: 
Your new dbt project "dbt_core_gold_employee_workforce" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:05:50.820855 [info ] [MainThread]: Setting up your profile.
[0m09:06:09.067985 [info ] [MainThread]: Profile dbt_core_gold_employee_workforce written to C:\Users\adolfo.arcoya\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:06:09.067985 [debug] [MainThread]: Command `dbt init` succeeded at 09:06:09.067985 after 31.12 seconds
[0m09:06:09.067985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F0298E1DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F02A5631D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04237AD50>]}
[0m09:06:09.067985 [debug] [MainThread]: Flushing usage events
[0m09:13:47.950525 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103DE3200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103DE3350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103DE31A0>]}


============================== 09:13:47.961123 | f3b76880-23d4-4ac8-a406-9b5a14d019ff ==============================
[0m09:13:47.961123 [info ] [MainThread]: Running with dbt=1.7.11
[0m09:13:47.961123 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\adolfo.arcoya\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m09:13:47.961123 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\dbt\dbt-core-gold-employee-workforce\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:13:47.961123 [debug] [MainThread]: Command `dbt deps` failed at 09:13:47.961123 after 0.79 seconds
[0m09:13:47.961123 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103954B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103DE28D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E103DE2960>]}
[0m09:13:47.961123 [debug] [MainThread]: Flushing usage events
[0m09:14:52.513022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7A3C29DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7A3C28710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7A3C29640>]}


============================== 09:14:52.528658 | 9cb671a3-bced-4150-a746-39f0651a9ee3 ==============================
[0m09:14:52.528658 [info ] [MainThread]: Running with dbt=1.7.11
[0m09:14:52.528658 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\adolfo.arcoya\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:14:52.528658 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\dbt\dbt-core-gold-employee-workforce\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:14:52.528658 [debug] [MainThread]: Command `dbt deps` failed at 09:14:52.528658 after 0.29 seconds
[0m09:14:52.528658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7A3A67DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7A39A1EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B79F30E270>]}
[0m09:14:52.528658 [debug] [MainThread]: Flushing usage events
[0m09:18:09.819084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D660579F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D660579730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D660579BB0>]}


============================== 09:18:09.819084 | dd4ed032-38dd-42f7-8f95-21b26a305480 ==============================
[0m09:18:09.819084 [info ] [MainThread]: Running with dbt=1.7.11
[0m09:18:09.819084 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\adolfo.arcoya\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:18:09.819084 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\dbt\dbt-core-gold-employee-workforce\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:18:09.819084 [debug] [MainThread]: Command `dbt deps` failed at 09:18:09.819084 after 0.25 seconds
[0m09:18:09.819084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D66028D820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D66049E990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D66047F950>]}
[0m09:18:09.819084 [debug] [MainThread]: Flushing usage events
